language: objective-c

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install carthage
install: carthage build --platform iOS

cache:
  directories:
  - Carthage/Build

notifications:
  email: false
  slack:
    secure: ijVeAxOpM7vEzrFzqSC5zpa7xuCFizuyou8cjcg+y6rz43S/PrhlIQDDxkTbbp/16MiVjckSo+CNf3RT3mjiheLARUwiqZn8lhETRis2qsP/idk6naByYbKfqnb/JreKXWuqXWKb27luD8nWN+kRvSckGRtpIqHpX4XDiwsfNfs=
